name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create deployment package
      run: |
        # Make startup script executable
        chmod +x startup.sh
        
        # Create deployment package
        zip -r deployment.zip . -x "*.git*"

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: home-tuition-app-2024
        package: deployment.zip
        startup-command: ./startup.sh

    - name: Configure Web App
      run: |
        az webapp config set --name home-tuition-app-2024 --resource-group home-tuition-rg --linux-fx-version "PYTHON|3.10"
        az webapp config appsettings set --name home-tuition-app-2024 --resource-group home-tuition-rg --settings \
          SCM_DO_BUILD_DURING_DEPLOYMENT=true \
          PYTHON_ENABLE_GUNICORN_MULTIWORKERS=1 \
          WEBSITES_PORT=8000
    
    - name: Azure Logout
      run: |
        az logout